"""Prueba

Revision ID: 47d8bf2334de
Revises: b040e6dba420
Create Date: 2024-02-13 18:58:05.609249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d8bf2334de'
down_revision: Union[str, None] = 'b040e6dba420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_task', sa.Column('prueba', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_task', 'prueba')
    # ### end Alembic commands ###
