"""Prueba2

Revision ID: 52250f3f6162
Revises: 47d8bf2334de
Create Date: 2024-02-13 19:00:52.088970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52250f3f6162'
down_revision: Union[str, None] = '47d8bf2334de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_task', 'prueba')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_task', sa.Column('prueba', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
