"""change_task_for_title

Revision ID: 99e88e06c6b9
Revises: 3f9eff06710c
Create Date: 2024-02-13 20:27:21.402338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e88e06c6b9'
down_revision: Union[str, None] = '3f9eff06710c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('tasks', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
