"""category_task_schema

Revision ID: b040e6dba420
Revises: b096b8374e2a
Create Date: 2024-02-12 14:55:16.942341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b040e6dba420'
down_revision: Union[str, None] = 'b096b8374e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_task_id'), 'category_task', ['id'], unique=False)
    op.create_index(op.f('ix_category_task_title'), 'category_task', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_task_title'), table_name='category_task')
    op.drop_index(op.f('ix_category_task_id'), table_name='category_task')
    op.drop_table('category_task')
    # ### end Alembic commands ###
