"""binnacle_table_add

Revision ID: e6eba909a846
Revises: 
Create Date: 2024-02-20 16:52:42.116117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6eba909a846'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('binnacles_user_id_fkey', 'binnacles', type_='foreignkey')
    op.drop_column('binnacles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binnacles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('binnacles_user_id_fkey', 'binnacles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
